# Generated by Django 4.0.3 on 2022-03-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_newstimeseries_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstimeseries',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
