# Generated by Django 4.0.3 on 2022-03-07 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_newstimeseries_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstimeseries',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.author'),
        ),
        migrations.AlterField(
            model_name='newstimeseries',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.publication'),
        ),
    ]
