# Generated by Django 4.0.3 on 2022-03-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_newstimeseries_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstimeseries',
            name='date',
            field=models.DateField(),
        ),
    ]
